namespace: my-app-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: europe-west3-docker.pkg.dev/meta-wording-487206-k0/arti-repo/my-app
    newTag: a685f42

replicas:
  - name: my-app
    count: 1